// *********************************************************************************
//
//		Created by SMS Export object wizard
//
//		Thursday, June 30, 2016 created
//
//		File Name: D:\healthcollections.MOF
//
// Comments :
//
//
// *********************************************************************************


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where ((DATEDIFF(hh, SMS_R_SYSTEM.AgentTime, getdate()) > 168) and AgentName = \"SMS_AD_SYSTEM_DISCOVERY_AGENT\")";
	QueryID = 1;
	RuleName = "Clients not found in AD in last 7 days";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608204941.000000+***";
	LastMemberChangeTime = "20160630204133.000000+***";
	LastRefreshTime = "20160630204133.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 760;
	MemberClassName = "";
	MemberCount = 760;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: AD Discovery: Older Than 7 Days";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608134100.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYSTEM.ResourceID,SYSTEM.ResourceType,SYSTEM.Name,SYSTEM.SMSUniqueIdentifier,SYSTEM.ResourceDomainORWorkgroup,SYSTEM.Client from SMS_R_System as system join SMS_FullCollectionMembership as collection on system.ResourceID = collection.ResourceID where collection.IsBlocked=1";
	QueryID = 1;
	RuleName = "Blocked Clients";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608205213.000000+***";
	LastMemberChangeTime = "20160608205223.000000+***";
	LastRefreshTime = "20160630205106.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Blocked Clients";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608135100.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType, SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier, SMS_R_SYSTEM.ResourceDomainORWorkgroup, SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_CM_RES_COLL_SMS00001 on SMS_CM_RES_COLL_SMS00001.ResourceId = SMS_R_System.ResourceId where SMS_CM_RES_COLL_SMS00001.IsApproved= '0'";
	QueryID = 1;
	RuleName = "Unapproved Clients";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608205213.000000+***";
	LastMemberChangeTime = "20160608205223.000000+***";
	LastRefreshTime = "20160630205106.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Unapproved Clients";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608135100.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****

// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where (AgentName in (\"Heartbeat Discovery\") and DATEDIFF(day,AgentTime,GetDate())>30)";
	QueryID = 1;
	RuleName = "Heartbeat (DDR) discovery older than 30 days";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608205706.000000+***";
	LastMemberChangeTime = "20160630205539.000000+***";
	LastRefreshTime = "20160630205539.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 401;
	MemberClassName = "";
	MemberCount = 401;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Heartbeat Discovery: Older Than 30 Days";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608135500.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYSTEM.ResourceID,SYSTEM.ResourceType,SYSTEM.Name,SYSTEM.SMSUniqueIdentifier,SYSTEM.ResourceDomainORWorkgroup,SYSTEM.Client from SMS_R_System as system join SMS_FullCollectionMembership as collection on system.ResourceID = collection.ResourceID where collection.IsDecommissioned=1";
	QueryID = 1;
	RuleName = "Decommisioned Clients";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608205849.000000+***";
	LastMemberChangeTime = "20160608205902.000000+***";
	LastRefreshTime = "20160630205827.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Decommissioned Clients";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608135800.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYS1.ResourceID,SYS1.ResourceType,SYS1.Name,SYS1.SMSUniqueIdentifier,SYS1.ResourceDomainORWorkgroup,SYS1.Client from SMS_R_System as SYS1 left join SMS_R_System as SYS2 on SYS2.SMSUniqueIdentifier = SYS1.SMSUniqueIdentifier where SYS1.ResourceId != SYS2.ResourceId";
	QueryID = 1;
	RuleName = "Duplicate SMS GUID";
}, 
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.ResourceId in (select SMS_R_System.ResourceId from SMS_R_System inner join SMS_G_System_SYSTEM on SMS_G_System_SYSTEM.ResourceID = SMS_R_System.ResourceId where (SMS_R_System.Name != SMS_G_System_SYSTEM.Name and SMS_G_System_SYSTEM.Name is not null )) and SMS_R_System.ResourceId in (select SMS_R_SYSTEM.ResourceID from SMS_R_System inner join SMS_G_System_CH_ClientSummary on SMS_G_System_CH_ClientSummary.ResourceId = SMS_R_System.ResourceId where SMS_G_System_CH_ClientSummary.ClientActiveStatus = 1)";
	QueryID = 2;
	RuleName = "Duplicate GUID 2";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608223002.000000+***";
	LastMemberChangeTime = "20160629210005.000000+***";
	LastRefreshTime = "20160630210040.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Duplicate SMS GUID";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608140000.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYS1.ResourceID,SYS1.ResourceType,SYS1.Name,SYS1.SMSUniqueIdentifier,SYS1.ResourceDomainORWorkgroup,SYS1.Client from SMS_R_System as SYS1   LEFT JOIN SMS_R_System as SYS2 ON SYS1.HardwareID = SYS2.HardwareID  where SYS1.ResourceID !=SYS2.ResourceID";
	QueryID = 1;
	RuleName = "Duplicate hardware ID";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608211046.000000+***";
	LastMemberChangeTime = "20160629210217.000000+***";
	LastRefreshTime = "20160630210254.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 7;
	MemberClassName = "";
	MemberCount = 7;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Duplicate Hardware ID";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608140200.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYS1.ResourceID,SYS1.ResourceType,SYS1.Name,SYS1.SMSUniqueIdentifier,SYS1.ResourceDomainORWorkgroup,SYS1.Client from SMS_R_System as SYS1 inner join SMS_R_System as SYS2 on SYS2.Name = SYS1.Name where SYS1.ResourceId != SYS2.ResourceId";
	QueryID = 1;
	RuleName = "Duplicate System name";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608211028.000000+***";
	LastMemberChangeTime = "20160630210827.000000+***";
	LastRefreshTime = "20160630210827.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 24;
	MemberClassName = "";
	MemberCount = 24;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Duplicate System Name";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608140800.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_COMPUTER_SYSTEM on SMS_G_System_COMPUTER_SYSTEM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_COMPUTER_SYSTEM.Name not in (select SMS_R_System.Name from SMS_R_System inner join SMS_G_System_WORKSTATION_STATUS on SMS_G_System_WORKSTATION_STATUS.ResourceID = SMS_R_System.ResourceId where SMS_G_System_WORKSTATION_STATUS.LastHardwareScan >= DateAdd(dd,-14,GetDate()) )";
	QueryID = 1;
	RuleName = "Hardware Inventory";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608211802.000000+***";
	LastMemberChangeTime = "20160630172338.000000+***";
	LastRefreshTime = "20160630172338.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 800;
	MemberClassName = "";
	MemberCount = 800;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Hardware Inventory: Older than 14 Days";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 7;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608141200.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.Active = 0";
	QueryID = 1;
	RuleName = "Inactive Clients";
}, 
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYSTEM.ResourceID,SYSTEM.ResourceType,SYSTEM.Name,SYSTEM.SMSUniqueIdentifier,SYSTEM.ResourceDomainORWorkgroup,SYSTEM.Client from SMS_R_System as system join SMS_FullCollectionMembership as collection on system.ResourceID = collection.ResourceID where collection.IsActive=0";
	QueryID = 2;
	RuleName = "Inactive Clients (FCM)";
}, 
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.Active != \"1\"";
	QueryID = 3;
	RuleName = "Inactive Clients 2";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608215113.000000+***";
	LastMemberChangeTime = "20160629110049.000000+***";
	LastRefreshTime = "20160630212035.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 4;
	MemberClassName = "";
	MemberCount = 4;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Inactive Clients";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608142000.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_LOGICAL_DISK on   SMS_G_System_LOGICAL_DISK.ResourceID = SMS_R_System.ResourceId where   (SMS_G_System_LOGICAL_DISK.FreeSpace < 5120 and   SMS_G_System_LOGICAL_DISK.DeviceID = \"C:\")";
	QueryID = 1;
	RuleName = "Low Disk Space";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160622235838.000000+***";
	LastMemberChangeTime = "20160608212632.000000+***";
	LastRefreshTime = "20160630212537.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Low Disk Space (<5 GB)";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608142500.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.Client is null or SMS_R_System.Client=0";
	QueryID = 1;
	RuleName = "No Client";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608212759.000000+***";
	LastMemberChangeTime = "20160630212750.000000+***";
	LastRefreshTime = "20160630212750.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 194;
	MemberClassName = "";
	MemberCount = 194;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: No Client Installed";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608142700.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_SYSTEM on SMS_G_System_SYSTEM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_SYSTEM.Domain is null";
	QueryID = 1;
	RuleName = "No Domain (System)";
}, 
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_COMPUTER_SYSTEM on SMS_G_System_COMPUTER_SYSTEM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_COMPUTER_SYSTEM.Domain is null";
	QueryID = 2;
	RuleName = "No Domain (Computer System)";
}, 
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_SYSTEM on SMS_G_System_SYSTEM.ResourceID = SMS_R_System.ResourceId inner join SMS_G_System_COMPUTER_SYSTEM on SMS_G_System_COMPUTER_SYSTEM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_SYSTEM.Domain = '' or SMS_G_System_COMPUTER_SYSTEM.Domain = ''";
	QueryID = 3;
	RuleName = "No Domain (Blank)";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608214756.000000+***";
	LastMemberChangeTime = "20160625213147.000000+***";
	LastRefreshTime = "20160630213128.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 1;
	MemberClassName = "";
	MemberCount = 1;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Not on Domain";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608143100.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.Obsolete = 1";
	QueryID = 1;
	RuleName = "Obsolete Clients";
}, 
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYSTEM.ResourceID,SYSTEM.ResourceType,SYSTEM.Name,SYSTEM.SMSUniqueIdentifier,SYSTEM.ResourceDomainORWorkgroup,SYSTEM.Client from SMS_R_System as system join SMS_FullCollectionMembership as collection on system.ResourceID = collection.ResourceID where collection.IsObsolete=1";
	QueryID = 2;
	RuleName = "Obsolete Clients (FCM)";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608213503.000000+***";
	LastMemberChangeTime = "20160629110446.000000+***";
	LastRefreshTime = "20160630213340.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 4;
	MemberClassName = "";
	MemberCount = 4;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Obsolete Clients";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608143300.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where ResourceId in (select ResourceID from SMS_R_System inner join SMS_G_System_LastSoftwareScan on SMS_G_System_LastSoftwareScan.ResourceID = SMS_R_System.ResourceId where DATEDIFF(dd,SMS_G_System_LastSoftwareScan.LastScanDate,GetDate()) > 21)";
	QueryID = 1;
	RuleName = "Software Inventory";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608213631.000000+***";
	LastMemberChangeTime = "20160630213551.000000+***";
	LastRefreshTime = "20160630213551.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 638;
	MemberClassName = "";
	MemberCount = 638;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Software Inventory Older than 21 Days";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608143500.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYSTEM.ResourceID,SYSTEM.ResourceType,SYSTEM.Name,SYSTEM.SMSUniqueIdentifier,SYSTEM.ResourceDomainORWorkgroup,SYSTEM.Client from SMS_R_System as system join SMS_FullCollectionMembership as collection on system.ResourceID = collection.ResourceID where collection.IsAssigned=0";
	QueryID = 1;
	RuleName = "Unassigned Clients";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608214129.000000+***";
	LastMemberChangeTime = "20160630213927.000000+***";
	LastRefreshTime = "20160630213927.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 44;
	MemberClassName = "";
	MemberCount = 44;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Unassigned Clients";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608143900.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SYS.ResourceID,SYS.ResourceType,SYS.Name,SYS.SMSUniqueIdentifier,SYS.ResourceDomainORWorkgroup,SYS.Client from sms_r_system as SYS join SMS_StatusMessage as stat on stat.machinename = SYS.name OR stat.machinename = SYS.NetbiosName where stat.ModuleName = \"SMS Client\" and stat.MessageID = 11416 and DateDiff(dd,stat.Time, GetDate()) <7";
	QueryID = 1;
	RuleName = "WUA Agent Error";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608214508.000000+***";
	LastMemberChangeTime = "20160608214513.000000+***";
	LastRefreshTime = "20160630214245.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: WUA Error 11416 in Last 7 Days";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608144200.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where resourceid in (select resourceid from SMS_CH_EvalResult where SMS_CH_EvalResult.Result = 1 and DATEDIFF(day,SMS_CH_EvalResult.EvalTime,GetDate())<=7)";
	QueryID = 1;
	RuleName = "CCMEval - No Status";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608222234.000000+***";
	LastMemberChangeTime = "20160630172356.000000+***";
	LastRefreshTime = "20160630222127.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 1;
	MemberClassName = "";
	MemberCount = 1;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: CCMEval – No Status in more than 7 days";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608152100.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where resourceid in (select resourceid from SMS_CH_EvalResult where SMS_CH_EvalResult.Result in (3,4,5) and DATEDIFF(day,SMS_CH_EvalResult.EvalTime,GetDate())<=7)";
	QueryID = 1;
	RuleName = "CCMEval - Failed";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608222408.000000+***";
	LastMemberChangeTime = "20160630172231.000000+***";
	LastRefreshTime = "20160630222339.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 6;
	MemberClassName = "";
	MemberCount = 6;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: CCMEval – Failed Status";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608152300.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.Name in (Select InsStrValue from SMS_StatusMessage as stat left outer join SMS_StatMsgAttributes as att on stat.recordid = att.recordid left outer join SMS_StatMsgInsStrings as ins on stat.recordid = ins.recordid WHERE (COMPONENT=\"SMS_CLIENT_CONFIG_MANAGER\") AND MessageID = 3014 AND Win32Error = 112 AND DATEDIFF(day,stat.Time,GetDate())<7) and SMS_R_System.ResourceId not in (select SMS_R_SYSTEM.ResourceID from SMS_R_System where SMS_R_System.Client = 1)";
	QueryID = 1;
	RuleName = "Client Not Installed and Error 112 No Disk Space during Client Push";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608222633.000000+***";
	LastMemberChangeTime = "20160608222645.000000+***";
	LastRefreshTime = "20160630222446.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Client Not Installed and Error 112 No Disk Space during Client Push*";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608152400.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.Name in (Select InsStrValue from SMS_StatusMessage as stat left outer join SMS_StatMsgAttributes as att on stat.recordid = att.recordid left outer join SMS_StatMsgInsStrings as ins on stat.recordid = ins.recordid WHERE (COMPONENT=\"SMS_CLIENT_CONFIG_MANAGER\") AND MessageID = 3014 AND Win32Error = 5 AND DATEDIFF(day,stat.Time,GetDate())<7) and SMS_R_System.ResourceId not in (select SMS_R_SYSTEM.ResourceID from SMS_R_System where SMS_R_System.Client = 1)";
	QueryID = 1;
	RuleName = "Client Not Installed and Error 5 Access Denied during Client Push";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608222741.000000+***";
	LastMemberChangeTime = "20160608222750.000000+***";
	LastRefreshTime = "20160630222658.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Client Not Installed and Error 5 Access Denied during Client Push";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608152600.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_COMPUTER_SYSTEM on SMS_G_System_COMPUTER_SYSTEM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_COMPUTER_SYSTEM.Model is null and SMS_R_System.ResourceId in (select ResourceId from SMS_G_System_CH_ClientSummary Where ClientActiveStatus = 1)";
	QueryID = 1;
	RuleName = "HINV Missing Info";
}, 
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.ResourceId not in (select SMS_R_SYSTEM.ResourceID from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId where SMS_G_System_OPERATING_SYSTEM.Caption like \"%Windows%\") and SMS_R_System.ResourceId in (select ResourceId from SMS_G_System_CH_ClientSummary Where ClientActiveStatus = 1)";
	QueryID = 2;
	RuleName = "HINV Missing Informatoin 2";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608222913.000000+***";
	LastMemberChangeTime = "20160630222805.000000+***";
	LastRefreshTime = "20160630222805.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 45;
	MemberClassName = "";
	MemberCount = 45;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Hardware Inventory Missing Information";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608152800.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.ResourceId not in (select SMS_R_SYSTEM.ResourceID from sms_r_system inner join SMS_UpdateComplianceStatus on SMS_UpdateComplianceStatus.machineid = sms_r_system.resourceid Join SMS_Softwareupdate on SMS_Softwareupdate.CI_ID = SMS_UpdateComplianceStatus.CI_ID where SMS_UpdateComplianceStatus.Status = 0 or SMS_UpdateComplianceStatus.Status = 1 or SMS_UpdateComplianceStatus.Status = 2 or SMS_UpdateComplianceStatus.Status = 3) and SMS_R_System.ResourceId in (select SMS_R_SYSTEM.ResourceID from SMS_R_System inner join SMS_G_System_CH_ClientSummary on SMS_G_System_CH_ClientSummary.ResourceId = SMS_R_System.ResourceId where SMS_G_System_CH_ClientSummary.ClientActiveStatus = 1)";
	QueryID = 1;
	RuleName = "Software Updates Compliance Status Missing";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608223103.000000+***";
	LastMemberChangeTime = "20160630223022.000000+***";
	LastRefreshTime = "20160630223022.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 80;
	MemberClassName = "";
	MemberCount = 80;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Software Updates Compliance Status Missing";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608153000.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.Name in (select SMS_StatusMessage.MachineName from SMS_StatusMessage LEFT OUTER JOIN SMS_StatMsgAttributes ON SMS_StatusMessage.RecordID = SMS_StatMsgAttributes.RecordID LEFT OUTER JOIN SMS_StatMsgInsStrings ON SMS_StatusMessage.RecordID = SMS_StatMsgInsStrings.RecordID where SMS_StatusMessage.MessageID = \"2719\" AND SMS_StatusMessage.Component = \"SMS_INVENTORY_DATA_LOADER\" and DateDiff(dd,SMS_StatusMessage.Time, GetDate()) <7)";
	QueryID = 1;
	RuleName = "HINV MIF Max File Size Exceeded";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608223401.000000+***";
	LastMemberChangeTime = "20160608223413.000000+***";
	LastRefreshTime = "20160630223123.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: HINV MIF Max File Size Exceeded";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608153100.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_SYSTEM.SMSUniqueIdentifier in (select instr.insstrvalue from SMS_StatusMessage as sm join SMS_StatInsStr as instr on sm.recordid=instr.recordid where sm.messageid = 5448 and instr.insstrvalue like \"GUID%\" and DateDiff(dd,sm.Time, GetDate()) < 7)";
	QueryID = 1;
	RuleName = "Clients Not Receiving Policy (Invalid Signature)";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160608223508.000000+***";
	LastMemberChangeTime = "20160608223517.000000+***";
	LastRefreshTime = "20160630223433.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Clients Not Receiving Policy (Invalid Signature)";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160608153400.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.OperatingSystemNameandVersion NOT LIKE \"%Windows 10%\" AND SMS_R_System.OperatingSystemNameandVersion NOT LIKE \"%Workstation 10.0%\" AND SMS_R_System.OperatingSystemNameandVersion NOT LIKE \"%Workstation 5.1%\" AND SMS_R_System.OperatingSystemNameandVersion NOT LIKE \"%Workstation 6.1%\"";
	QueryID = 1;
	RuleName = "Operating Systems other than XP/7/10";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = TRUE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160613223550.000000+***";
	LastMemberChangeTime = "20160630172331.000000+***";
	LastRefreshTime = "20160630222552.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 39;
	MemberClassName = "";
	MemberCount = 39;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: Operating System is not XP/7/10";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160613152500.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****


// ***** Class : SMS_Collection *****
[SecurityVerbs(1342176935)]
instance of SMS_Collection
{
	CollectionID = "";
	CollectionRules = {
instance of SMS_CollectionRuleQuery
{
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.SMSAssignedSites NOT IN (\"ABC\", \"123\", \"DOH\", \"RAY\", \"ME\")";
	QueryID = 1;
	RuleName = "Site Code missing";
}};
	CollectionType = 2;
	CollectionVariablesCount = 0;
	Comment = "";
	CurrentStatus = 0;
	HasProvisionedMember = FALSE;
	IncludeExcludeCollectionsCount = 0;
	IsBuiltIn = FALSE;
	IsReferenceCollection = FALSE;
	ISVData = NULL;
	ISVDataSize = 0;
	ISVString = "";
	LastChangeTime = "20160615191639.000000+***";
	LastMemberChangeTime = "20160615191625.000000+***";
	LastRefreshTime = "20160630191227.000000+***";
	LimitToCollectionID = "";
	LimitToCollectionName = "";
	LocalMemberCount = 0;
	MemberClassName = "";
	MemberCount = 0;
	MonitoringFlags = 0;
	Name = "Client Health: Unhealthy: No Site Code (CHANGE SITE CODE)";
	OwnedByThisSite = TRUE;
	PowerConfigsCount = 0;
	RefreshSchedule = {
instance of SMS_ST_RecurInterval
{
	DayDuration = 0;
	DaySpan = 1;
	HourDuration = 0;
	HourSpan = 0;
	IsGMT = FALSE;
	MinuteDuration = 0;
	MinuteSpan = 0;
	StartTime = "20160615121200.000000+***";
}};
	RefreshType = 2;
	ServiceWindowsCount = 0;
};
// ***** End *****
